### ISSUE TITLE
Easy install script.

### ISSUE THREAD

**Issue by slyfox1186** [yunchih/static-binaries#3]
Just wanted you to have this. I really liked your repository. Very neat. Maybe this can help someone you know.

[Easy Install Script for static-binaries](https://github.com/slyfox1186/pihole-regex/blob/main/scripts/unrelated/youchin.sh)

**Comment by edwinjhlee** [comment]
> Just wanted you to have this. I really liked your repository. Very neat. Maybe this can help someone you know.
> 
> [Easy Install Script for static-binaries](https://github.com/slyfox1186/pihole-regex/blob/main/scripts/unrelated/youchin.sh)

I think you might probably have interest. They are all portable tools.
https://x-cmd.com/pkg

Also, cosmo.
https://x-cmd.com/mod/cosmo

**Comment by slyfox1186** [comment]
sweet thanks for that.
